services:

  testing-platform:
    build:
      context: ../..
      dockerfile: compose/staging/Dockerfile
      cache_from:
        - testing-platform:app
    image: "testing-platform:app"
    restart: unless-stopped
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: testing_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: change_me
    command: gunicorn testing_platform.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../../static:/var/www/testing_platform/static
    expose:
      - 8000

  nginx:
    build:
      context: ../../nginx
      cache_from:
        - testing-platform:nginx
    image: "testing-platform:nginx"
    restart: unless-stopped
    volumes:
      - ../../static:/var/www/testing_platform/static
    ports:
      - '80:80'
    depends_on:
      - testing-platform

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: testing_platform
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  static:
  pgdata:
